[package]
name = "oblast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
paste = "1.0.4"
blst = "0.3.10"
num-bigint = "0.3.1"